version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Django-Poll-App
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
  AfterInstall:
      - location: scripts/after_install.sh