version: 0.1 

environment_variables: 
   plaintext: 
     DJANGO_SETTINGS_MODULE: pollme.settings 
     SECRET_KEY: nosecret 
     DATABASE_DEFAULT_URL: sqlite:///db.sqlite3 
     DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3 
     OPBEAT_ENABLED: False 
phases: 
  pre_build: 
    commands: 
      - echo Prebuild ops 
      - pip3 install -r requirements.txt 
      - python3 manage.py makemigrations
      - python3 manage.py migrate
  build: 
    commands: 
      - echo Building the application 
      - python manage.py runserver 
  post_build: 
    commands: 
      - echo Build completed on `date`