name: Build and Deploy to Master

on:
  push:
    branches:
      - master
                                               
jobs:
  build-deploy:
    name: Build and Deploy to Master Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.9.10
        uses: actions/setup-python@v3
        with: 
          python-version: "3.9.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==22.10.0 flake8==6.0.0 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true